3-Django/app/config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

3-Django/app/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    # ex: /artichoke-dip/
    path('<slug:slug>/',
        views.RecipeDetailView.as_view(),
        name='detail'),
]

3-Django/cookbook/recipes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /artichoke-dip/
    url(r'^(?P<slug>[-\w\d]+)/$',
        views.RecipeDetailView.as_view(),
        name='detail'),
]

3-Django/app/recipes/models.py
from django.db import models

from . import utils


class Category(models.Model):
    """
    A category of recipes used to search and organize.
    """
    name = models.CharField(max_length=50)
    name_plural = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    ordinal = models.IntegerField(unique=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('ordinal', )

    def __str__(self):
        return self.name


class Recipe(models.Model):
    """
    A recipe.
    """
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField()
    prep_time = models.DurationField(blank=True, null=True)
    wait_time = models.DurationField(blank=True, null=True)
    cook_time = models.DurationField(blank=True, null=True)
    yields = models.CharField(max_length=100, blank=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='recipes')

    def get_prep_time(self):
        return utils.format_duration(self.prep_time)

    def get_wait_time(self):
        return utils.format_duration(self.wait_time)

    def get_cook_time(self):
        return utils.format_duration(self.cook_time)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'recipe'
        verbose_name_plural = 'recipes'


class Ingredient(models.Model):
    """
    A recipe ingredient, including an amount, a unit, and a food.
    """
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               related_name='ingredients')
    quantity = models.FloatField()
    unit = models.CharField(max_length=50, blank=True)
    food = models.CharField(max_length=50)

    def text(self):
        return utils.format_quantity(self.quantity, self.unit, self.food)

    def __str__(self):
        return '{recipe}: {quantity} {unit} {food}'.format(
            recipe=str(self.recipe),
            quantity=str(self.quantity),
            unit=str(self.unit),
            food=str(self.food),
        )

    class Meta:
        ordering = ('id', )


class Direction(models.Model):
    """
    A step in a recipe's directions.
    """
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               related_name='directions')
    text = models.TextField()
    ordinal = models.IntegerField()

    class Meta:
        ordering = ['recipe', 'ordinal', ]

    def __str__(self):
        return '{recipe} ({ordinal}): {text}'.format(
            recipe=str(self.recipe),
            ordinal=self.ordinal,
            text=self.text[:100],
        )

3-Django/cookbook/recipes/models.py
from django.db import models

from . import utils


class Category(models.Model):
    """
    A category of recipes used to search and organize.
    """
    name = models.CharField(max_length=50)
    name_plural = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    ordinal = models.IntegerField(unique=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('ordinal', )

    def __str__(self):
        return self.name


class Recipe(models.Model):
    """
    A recipe.
    """
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField()
    prep_time = models.DurationField(blank=True, null=True)
    wait_time = models.DurationField(blank=True, null=True)
    cook_time = models.DurationField(blank=True, null=True)
    yields = models.CharField(max_length=100, blank=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='recipes')

    def get_prep_time(self):
        return utils.format_duration(self.prep_time)

    def get_wait_time(self):
        return utils.format_duration(self.wait_time)

    def get_cook_time(self):
        return utils.format_duration(self.cook_time)

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    """
    A recipe ingredient, including an amount, a unit, and a food.
    """
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               related_name='ingredients')
    quantity = models.FloatField()
    unit = models.CharField(max_length=50, blank=True)
    food = models.CharField(max_length=50)

    def text(self):
        return utils.format_quantity(self.quantity, self.unit, self.food)

    def __str__(self):
        return '{recipe}: {quantity} {unit} {food}'.format(
            recipe=str(self.recipe),
            quantity=str(self.quantity),
            unit=str(self.unit),
            food=str(self.food),
        )

    class Meta:
        ordering = ('id', )


class Direction(models.Model):
    """
    A step in a recipe's directions.
    """
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               related_name='directions')
    text = models.TextField()
    ordinal = models.IntegerField()

    class Meta:
        ordering = ['recipe', 'ordinal', ]

    def __str__(self):
        return '{recipe} ({ordinal}): {text}'.format(
            recipe=str(self.recipe),
            ordinal=self.ordinal,
            text=self.text[:100],
        )

3-Django/app/recipes/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from .models import Category, Recipe

class RecipeDetailView(DetailView):
    model = Recipe

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

3-Django/templates/_sidebar.html
<div id="sidebar" class="ui left vertical inverted menu">
  <div class="toc">
    {% for category in category_list %}
      <div class="item">
        <div class="header">{{ category.name_plural }}</div>
        <div class="menu">
          {% for r in category.recipes.all %}
            <a class="{% if r == recipe %}active{% endif %} item"
               href="{% url 'recipes:detail' r.slug %}">{{ r }}</a>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
</div>

3-Django/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html>

  <head>
  	<meta charset="utf-8">
  	<title>3 - {% block title %} {% endblock title %}</title>

  	<!-- Stylesheets -->
  	<link rel="stylesheet" href="{% static '/css/semantic.css' %}">
  	<link rel="stylesheet" href="{% static '/css/recipe.css' %}">
  </head>

  <body>
  	<div id="content">
  		{% include '_sidebar.html' %}

      {% block content %} {% endblock content %}

  	</div>
  </body>
</html>

3-Django/templates/recipes/recipe_detail.html
{% extends 'base.html' %}

{% block title %}
{{ recipe }}
{% endblock title %}

{% block content %}
<div id="recipe-container">
  <div id="recipe">
    <div class="ui basic center aligned segment">
      <h1 class="ui header">{{ recipe.title }}</h1>
      <p>{{ recipe.description }}</p>
      {% if recipe.yields %}
        <p>
          <strong>Yields:</strong> {{ recipe.yields }}
        </p>
      {% endif %}
      {% if recipe.prep_time or recipe.wait_time or recipe.cook_time %}
        <div class="ui message">
          <i class="wait icon"></i>
          {% if recipe.prep_time %}
            <span class="timer"><strong>Prep:</strong> {{ recipe.get_prep_time }}</span>
          {% endif %}
          {% if recipe.wait_time %}
            <span class="timer"><strong>Wait:</strong> {{ recipe.get_wait_time }}</span>
          {% endif %}
          {% if recipe.cook_time %}
            <span class="timer"><strong>Cook:</strong> {{ recipe.get_cook_time }}</span>
          {% endif %}
        </div>
      {% endif %}
    </div>
    <div class="ui stackable grid">
      <div class="six wide column">
        <h2 class="ui header">Ingredients</h2>
        <div class="ui relaxed list">
          {% for ingredient in recipe.ingredients.all %}
            <div class="ui item">
              <i class="square outline icon"></i>
              <div class="content">
                {{ ingredient.text }}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="ten wide column">
        <h2 class="ui header">Directions</h2>
        <ol class="ui relaxed list">
          {% for direction in recipe.directions.all %}
            <li class="item">
              {{ direction.text }}
            </li>
          {% endfor %}
        </ol>
      </div>
    </div>
  </div>
</div>
{% endblock content %}